Update ViewController.swift
IBM/ar-resume-with-visual-recognition pull request #33
Opened 2018-10-04 12:45 UTC by Julz4455

2018-10-04 13:49 UTC, stevemar approved these changes
no new functionality here, but it's a worthwhile change for consistency in error messages

2018-10-04 15:46 UTC, sanjeevghimire requested changes

2018-10-04 15:46 UTC, sanjeevghimire commented on ios_swift/ResumeARStarter/ViewController.swift
> +    print("Starting!")
why is a print statement needed here?

2019-01-12 04:19 UTC, stevemart commented
Covered by https://github.com/IBM/ar-resume-with-visual-recognition/pull/37

2019-01-12 04:19 UTC, closed without merging